### ISSUE TITLE
Memory leaks and crashes when running certain ImageMagick commands

### ISSUE THREAD

**Issue by HIDEN64** [HIDEN64/HBot#3]
There is a known bug where there are memory leaks and crashes when running certain ImageMagick commands, and they seem to happen at random.

It is believed that this bug is Linux only, I have yet to see it occur on Windows or macOS. If anyone can test this/in general assist with this bug, that would be greatly appreciated.

**Comment by HIDEN64** [comment]
Can confirm this bug is Linux only. The live instance of the bot now runs on Windows, and I have not had this issue once since the switch.

**Comment by nick99nack** [comment]
Windows Power:tm:

**Comment by dkay0670** [comment]
yes

**Comment by HIDEN64** [comment]
This seems to be a bug relating to Magick.NET/ImageMagick, not HBot itself.

Closing. Not related to HBot itself.
